ansible_ssh_user: admin
ansible_ssh_pass: admin
ansible_network_os: dellemc.os10.os10

os10_system:
  hostname: "leaf1"

os10_bgp:
  asn: 65101
  router_id: 192.168.1.103
  neighbor: 
    - type: ipv4 
      interface: vlan20
      send_community:
        - type: extended
          state: present
      address_family: 
        - type: l2vpn
          activate: true
          state: present
      admin: up
      state: present
    - type: ipv4 
      interface: vlan10
      send_community:
        - type: extended
          state: present
      address_family: 
        - type: l2vpn
          activate: true
          state: present
      admin: up
      state: present
    - type: ipv4
      interface: vlan11
      send_community:
        - type: extended
          state: present
      address_family: 
        - type: l2vpn
          activate: true
          state: present
      admin: up
      state: present
  ipv4_network: 10.1.1.1/32
  redistribute:
    - route_type: connected
      address_type: ipv4   
      state: present
  state: "present"


os10_interface:
  loopback 0:
    admin: up
    ip_and_mask: 10.1.1.1/32
  ethernet 1/1/6:
    switchport: False
    admin: up
  ethernet 1/1/4:
    admin: up
    switchport: False
  ethernet 1/1/5:
    admin: up
    switchport: False
  ethernet 1/1/1:
    admin: up
    switchport: False
    portmode: "trunk"
#  ethernet 1/1/2:
  ethernet 1/1/3:
    admin: up
    switchport: False
    portmode: "trunk"
  port-channel 10:
    portmode: "trunk"
    admin: up
  vlan 10:
    suppress_ra: absent
    min_ra: 3
    max_ra: 4
    admin: up
  vlan 11:
    suppress_ra: absent
    min_ra: 3
    max_ra: 4
    admin: up
  vlan 20:
    suppress_ra: absent
    min_ra: 3
    max_ra: 4
    admin: up
  virtual-network 100:
    vrf: "test"
    ip_and_mask: "172.16.1.1/24"
    ip_virtual_gateway_ip: "172.16.1.254"
    admin: up
  virtual-network 300:
    vrf: "test"
    ip_and_mask: "172.17.1.1/24"
    ip_virtual_gateway_ip: "172.17.1.254"
    admin: up

os10_lag:
  port-channel 10:
    type: dynamic
    channel_members:
#   - port: ethernet1/1/5
      - port: ethernet1/1/4
        mode: active
    state: present

os10_vlan:
  vlan 10:
    tagged_members:
      - port: ethernet 1/1/52
        state: "present"
        access_vlan: "false"
    state: "present"
  vlan 20:
    tagged_members:
#      - port: ethernet 1/1/2
      - port: ethernet 1/1/51
        state: "present"
        access_vlan: "false"
    state: "present"

os10_vrf:
  vrfdetails:
    - vrf_name: "tenant1"
      state: "present"

os10_vxlan:
    anycast_gateway_mac: "00:00:aa:bb:ee:ff"
    nve:
      source_interface: 0
      state: "present"
    evpn:
      evi:
        - id: 100
          vni:
            id: 100
            state: "present"
          rd: "auto"
          route_target:
            - type: "manual"
              asn_value: "65530:65532"
              route_target_type: "both"
              state: "present"
          state: "present"
        - id: 300
          vni:
            id: 300
            state: "present"
          rd: "auto"
          route_target:
            - type: "auto"
              state: "present"
          state: "present"
      vrf:
        - name: "tenant1"
          vni: 1000
          adv_ipv4: 
            - type: "connected"
              state: "present"
            - type: "bgp"
              state: "present"
          route_target:
            - type: "manual"
              asn_value: "65530:65534"
              route_target_type: "both"
              state: "present"
      rmac: 00:11:11:11:11:11
      dis_rt_asn: "true"
    virtual_network:
      virtual_net:
        - id: 100
          vlt_vlan_id: 100
          member_interface:
            - ifname: "port-channel10"
              type: "tagged"
              vlanid: 100
              state: "present"
          vxlan_vni:
            id: 100
            state: "present"
          state: "present"
        - id: 300
          vlt_vlan_id: 300
          member_interface:
            - ifname: "port-channel10"
              type: "tagged"
              vlanid: 300
              state: "present"
          vxlan_vni:
            id: 300
            state: "present"
          state: "present"

os10_vlt:
   domain: 1
   destination_type: "ipv4"
   peer_routing: True
#   discovery_intf: "1/1/3-1/1/4"
   discovery_intf: "1/1/53-1/1/54"
   vlt_mac: 00:00:00:11:22:33
   vlt_peers:
     Po 10:
        peer_lag: 10
   state: "present"