ansible_ssh_user: admin
ansible_ssh_pass: admin
ansible_network_os: dellemc.os10.os10

os10_system:
  hostname: "leaf4"

os10_bgp:
  asn: 65102
  router_id: 192.168.1.106
  neighbor: 
    - type: ipv4 
      interface: vlan70
      send_community:
        - type: extended
          state: present
      address_family: 
        - type: l2vpn
          activate: true
          state: present
      admin: up
      state: present
    - type: ipv4 
      interface: vlan80
      send_community:
        - type: extended
          state: present
      address_family: 
        - type: l2vpn
          activate: true
          state: present
      admin: up
      state: present
    - type: ipv4 
      interface: vlan11
      send_community:
        - type: extended
          state: present
      address_family: 
        - type: l2vpn
          activate: true
          state: present
      admin: up
      state: present
  vrf:
    name: "test"
    address_type: ipv4 
    redistribute:
      - route_type: l2vpn 
  ipv4_network: 10.1.1.2/32
  redistribute:
    - route_type: connected
      address_type: ipv4   
      state: present
  state: "present"


os10_interface:
  loopback 0:
    admin: up
    ip_and_mask: 10.1.1.2/32
  loopback 10:
    admin: up
    vrf: "test"
    ip_and_mask: 80.1.1.10/32
  loopback 20:
    admin: up
    vrf: "test"
    ip_and_mask: 90.1.1.10/32
  ethernet 1/1/1:
    admin: up
    switchport: False
    portmode: "trunk"
  ethernet 1/1/2:
    admin: up
    switchport: False
    portmode: "trunk"
  ethernet 1/1/3:
    switchport: False
    admin: up
  ethernet 1/1/4:
    admin: up
    switchport: False
  ethernet 1/1/5:
    switchport: False
    vrf: "test"
    ip_and_mask: "20.20.20.20/24"
    admin: up
  port-channel 10:
    portmode: "trunk"
    admin: up
  vlan 11:
    suppress_ra: absent
    min_ra: 3
    max_ra: 4
    admin: up
  vlan 70:
    suppress_ra: absent
    min_ra: 3
    max_ra: 4
    admin: up
  vlan 80:
    suppress_ra: absent
    min_ra: 3
    max_ra: 4
    admin: up
  virtual-network 200:
    vrf: "test"
    ip_and_mask: "172.16.1.4/24"
    ip_virtual_gateway_ip: "172.16.1.254"
    admin: up
  virtual-network 300:
    vrf: "test"
    ip_and_mask: "172.17.1.4/24"
    ip_virtual_gateway_ip: "172.17.1.254"
    admin: up

os10_vlan:
  vlan 70:
    tagged_members:
      - port: ethernet 1/1/52
        state: "present"
        access_vlan: "false"
    state: "present"
  vlan 80:
    tagged_members:
      - port: ethernet 1/1/51
        state: "present"
        access_vlan: "false"
    state: "present"

os10_vrf:
  vrfdetails:
    - vrf_name: "tenant1"
      state: "present"

os10_vxlan:
    anycast_gateway_mac: "00:01:aa:bb:ee:ff"
    nve:
      source_interface: 0
      state: "present"
    evpn:
      evi:
        - id: 200
          vni:
            id: 200
            state: "present"
          rd: "auto"
          route_target:
            - type: "manual"
              asn_value: "65530:65533"
              route_target_type: "both"
              state: "present"
          state: "present"
        - id: 300
          vni:
            id: 300
            state: "present"
          rd: "auto"
          route_target:
            - type: "auto"
              state: "present"
          state: "present"
      vrf:
        - name: "tenant1"
          vni: 1000
          adv_ipv4: 
            - type: "connected"
              state: "present"
            - type: "bgp"
              state: "present"
          route_target:
            - type: "manual"
              asn_value: "65530:65534"
              route_target_type: "both"
              state: "present"
      rmac: 00:11:11:11:11:11
      dis_rt_asn: "true"
    virtual_network:
      virtual_net:
        - id: 200
          vlt_vlan_id: 200
          vxlan_vni:
            id: 200
            state: "present"
          state: "present"
        - id: 300
          vlt_vlan_id: 300
          vxlan_vni:
            id: 300
            state: "present"
          state: "present"

os10_vlt:
   domain: 1
   destination_type: "ipv4"
   peer_routing: True
   discovery_intf: "1/1/53-1/1/54"
   vlt_mac: 00:00:00:11:22:33
   vlt_peers:
     Po 10:
        peer_lag: 10
   state: "present"